packages: []
catalogs:
  build:
    tsdown: ^0.13.0
  cli:
    bumpp: ^10.2.1
    czg: ^1.12.0
    pncat: ^0.4.0
    taze: ^19.1.0
  dev:
    '@octohash/tsconfig': ^0.1.0
    typescript: ^5.8.3
  lint:
    '@antfu/eslint-config': ^5.0.0
    eslint: ^9.32.0
    eslint-flat-config-utils: ^2.1.1
    eslint-plugin-format: ^1.0.1
    eslint-plugin-tailwindcss: ^4.0.0-beta.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
  node:
    local-pkg: ^1.1.1
    pathe: ^2.0.3
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.1.0
